name: "Publish library"
on:
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: "Library version"
        required: true
      releaseDescription:
        description: "Release description"
        required: true
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: 'echo -n ${{ github.event.inputs.libraryVersion }} > version.txt'
        shell: bash

      - name: Check permissions
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `check` step
      - name: Check permissions
        if: "! steps.check.outputs.has-permission"
        run: exit 1

      - name: Increase version
        uses: ./.github/actions/commit_and_push
        if: steps.check.outputs.has-permission
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Library
        run: 'bash ./gradlew clean check assemble'

      - name: Create Release in github
        if: steps.check.outputs.has-permission
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.libraryVersion }}
          release_name: ${{ github.event.inputs.libraryVersion }}
          body: ${{ github.event.inputs.releaseDescription }}
          draft: true
          prerelease: false
