name: "Run tests"
on:
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: "Lint & Detekt"
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: 'bash ./gradlew detekt check'
