name: "Run tests"
on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run checks
        if: success() || failure()
        run: ./gradlew check

      - name: Run Detekt
        if: success() || failure()
        run: ./gradlew detekt
